[project]
name = "ai-native-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "roarjang", email = "roarjang@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
ai-native-service = "ai_native_service:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
